### ISSUE TITLE
Documentation unreadble, style.css not loading

### ISSUE THREAD

**Issue by ElliotNB** [wildhaber/nativeDroid2#107]
@wildhaber The primary CSS file for http://nativedroid.scripter.click/  ( http://nativedroid.scripter.click/wp-content/themes/twentyfifteen/style.css?ver=4.8.6 ) isn't loading -- it's returning an HTTP 522 error (Origin Connection Time-out). The documentation is unreadable without that CSS file.

I'd love to look through the docs and use this library on an older jQuery Mobile project (1.4.5) that needs re-skinning. Happy to contribute bug fixes and minor enhancements as I encounter them.

**Comment by wildhaber** [comment]
Hey @ElliotNB ,

Thanks for your notice. Unfortunately I cannot reproduce the not loading css-file. It works quite well on my side. There might could have been a temporary issue with the server. 

Nevertheless, I might should reconsider moving the documentation to github directly.

Happy to have your feedback and welcome any contribution 👍 

Regards,
Raphael

**Comment by ElliotNB** [comment]
Hmm, that's really strange. For the past couple days this is what the documentation looks like for me: 

![image](https://user-images.githubusercontent.com/14059303/40390883-79ab453c-5dcb-11e8-90ef-2bd04422cfc5.png)

But it must be my local ISP, because I just tested it on my phone on a different Internet connection and it loads fine...

Sorry for the hassle and thank you for publishing such a great JQM theme!
