### ISSUE TITLE
Open Popup Dailog programmatically

### ISSUE THREAD

**Issue by damtaipu** [wildhaber/nativeDroid2#110]
This is a simple problem: how to open a Dialog popup programmatically??

**Comment by damtaipu** [comment]
**Can someone help me???**

**Comment by pazDontExist** [comment]
Hi, 
actually is very simple. 

all the information you need can be found at this [link](http://demos.jquerymobile.com/1.4.5/popup/)

Have a nice day

**Comment by damtaipu** [comment]
> Hi,
> actually is very simple.
> 
> all the information you need can be found at this [link](http://demos.jquerymobile.com/1.4.5/popup/)
> 
> Have a nice day

**Problem solved. Thank you very much**

**Comment by pazDontExist** [comment]
you're welcome

**Comment by damtaipu** [comment]
tkn
