### ISSUE TITLE
Cant work whit nativedroid2 (DEMO)

### ISSUE THREAD

**Issue by hitmacreed** [wildhaber/nativeDroid2#67]
Cant work whit nativedroid2  i have on wamp server but it wont work  i get this
![sem titulo](https://cloud.githubusercontent.com/assets/17566079/14405860/1a9715cc-fe90-11e5-8ce6-91ad50461b84.png)
 but when i open a page on left panel i get a blank page 
![sem titulo](https://cloud.githubusercontent.com/assets/17566079/14406083/1daa4d6e-fe96-11e5-8e84-be8f3f5db715.png)

**Comment by joblesspoet** [comment]
Please paste the link url from your left panel. Before that check if the page exist on the same location or not under "nativeDroid2-master" directory
