### ISSUE TITLE
The sp units in CSS

### ISSUE THREAD

**Issue by taneltm** [wildhaber/nativeDroid2#74]
In nativedroid2.css, there are 2 places where `sp` units are used.
1. `h4 { font-size: 2sp; line-height: 1.2em; font-weight: 500; }`
2. `.nd2-title { font-size: 2sp; line-height: 1.2em; font-weight: 500; display: block; }`

The sp unit (Scale-independent pixels) is not supported in CSS3.
It looks like a mistake and I'm guessing it should be 18px or 20px instead of 2sp.

Also h4 is the only heading element that has font-weight 500, is that really how it should be?

And last but not least:
```
.nd2-sidepanel-profile .profile-text strong {
	font-size: 2p;
	...
}
```
I'm guessing that's the `sp` unit with a typo? :)

I would do a pull request, but I'm not 100% sure what those values should be in pixels.

**Comment by wildhaber** [comment]
hey @taneltm thanks for input, true, those values are errors when I took them from the specs - https://material.google.com/style/typography.html#typography-styles.

`h4` and `.nd2-title` should be `20px` while the `font-weight: 500;` is correct.

as well as yes, the `.nd2-sidepanel-profile .profile-text strong` should have a `font-size: 20px;`

I'd really appreciate a PR :-)
