### ISSUE TITLE
dynamic creation of listview elements doesn't produce them in the same style.

### ISSUE THREAD

**Issue by bryancresswell** [wildhaber/nativeDroid2#90]
When I create a listview element dynamically, it doesn't give me the desired style. It only works if I add it dynamically. Any help?

`function appendToList() { 
  if (!listCreated) {
    $("#chooseExhibition").append("<ul id='list' data-role='listview' data-icon='false' style='padding-top:10px;'></ul>");
    listCreated = true;
    $("#chooseExhibition").trigger("create");
  } // need to check here for firebase if the exhibition is in the database (Do a simple if-else to check if data[0] is in the database)
  $("#list").append("<li style='font-family: 'Quicksand', sans-serif !important;'><a href='javascript:pageGenerator()'>Hello</a></li>");
  resetData();
  }`

**Comment by pazDontExist** [comment]
try to add .listview( "refresh" )

$("#chooseExhibition").append("<ul id='list' data-role='listview' data-icon='false' style='padding-top:10px;'></ul>").listview( "refresh" );
